[AppSettings]
APP_VERSION = "0.0.5.1"
SERVER_NAME = "0.0.0.0"
PORT = 7860
SERVER_PORT = 8171
TITLE = "EdFitter"
CSS_PATH = "app.css"
QUALITY = true
DB = "edfitter.duckdb"

[AppInfo]
DURATION = 5
TITLE = "Информация"
MODEL = "Модель для сопоставления вакансии с ПУДами изменена на {}"

[InformationMessages]
NOTI_IN_DEV = "В разработке"
STEP_1 = "Вход в систему"
STEP_2 = "Чат"
INSTRUCTION = "Инструкция для участников в рамках \"массового\"/\"экспертного\" тестирования"
NOTI_AUTH = [
    "Для входа в систему EdFitter заполните поля выше",
    "Все данные пользователя успешно заполнены",
]
SKILLS_NOT_DEFINED = "Навыки не определены"
LEVEL_NOT_DEFINED = "Курс обучения не указан"
FROM_TO = "От {} до {}"
MODEL = "Выберите модель"
COURSES_GRADES = "Выберите варианты оценок (возможен множественный выбор)"
COURSES_GRADES_DATA = [
    "Данных по",
    "нет"
]
COURSES_GRADES_NOT_DEFINED = [
    "средней оценке",
    "статистической погрешности средней оценки",
    "медианной оценке",
    "статистической погрешности медианной оценки",
    "индексу сложности освоения курса №1 (метрика Вассерштейна)",
    "статистической погрешности индекса №1",
    "индексу сложности освоения курса №2 (по средней оценке)",
    "статистической погрешности индекса №2",
    "индексу сложности освоения курса №3 (по медианной оценке)",
    "статистической погрешности индекса №3",
]

[OtherMessages]
IMPORTANT = "Обязательно"
ACCOUNT = "Персональные данные"
HIDE_ACCOUNT = "Скрыть персональные данные"
AUTH = "Запомнить данные пользователя"
JOB_DESC = "Ввод запроса"
EVALUATE = "Сохранить ответы"
START_EVALUATE = "Понятно, начать"

[Labels]
GROUP_NUMBER = "Номер группы (только для студентов)"
USERNAME = "Имя пользователя"
USER_ROLE = "Роль или направление"
CHATBOT = "Для получения рекомендаций по выбору учебных курсов введите в строку ниже описание интересующей вас вакансии, профессии или сферы занятости"
TOP_SUBJECTS = "Количество предлагаемых предметов"
MAX_SKILL_WORDS = "Максимальное количество слов в одном навыке"
MODEL = "Модель для сопоставления вакансии с ПУДами"
COURSES_GRADES = "Показатели успеваемости студентов"
ADD_VACANCY_SKILLS = "Перечислите навыки, которые по Вашему мнению, важны, но отсутствуют в выдаче, нажимая стрелку справа после ввода каждого навыка"
FEEDBACK = "Что следует изменить в приложении, чтобы его улучшить? Какие еще у Вас есть комментарии, в том числе по системе оценки качества приложения?"

[EducationLevels]
ALL_LEVELS = "Бакалавриат, Специалитет, Магистратура, Аспирантура"
NONE_LEVELS = "None"

[HtmlContent]
LEVELS_EDUCATION_LABEL = "Уровни обучения:"
LEVEL_EDUCATION_LABEL = "Уровень обучения:"
NUMBERS_EDUCATION = "Курсы обучения:"
NUMBER_EDUCATION = "Курс обучения:"
SUBJECT_RELEVANCE = "Релевантность курса запросу:"
SUBJECT_LABEL = "Дисциплина:"
ID_SUBJECT_LABEL = "ID дисциплины:"
DEPARTMENT_LABEL = "Кафедра:"
FACULTY_LABEL = "Факультет кафедры:"
CAMPUS_LABEL = "Кампус:"
AUDIENCE_LABEL = "Охват аудитории:"
FORMAT_LABEL = "Формат изучения:"
SKILLS_LABEL = "Получаемые навыки:"
VACANCY_LABEL_STATIC = "Требуемые навыки:"
VACANCY_LABEL = "Требуемые навыки ({}):"
VACANCY_LABEL_CLICK = "кликните все неподходящие навыки"
COURSES_GRADES = "Метрики курса:"
USEFULNESS_CURRENT = "Насколько полезно данное приложение в его нынешнем виде?"
DEMAND_CURRENT = "Насколько было бы востребовано данное приложение в доработанном виде?"
INTERFACE_CURRENT = "Насколько удобен интерфейс в его нынешнем виде?"

[TabCreators]
"Приложение" = "app_tab"
"Настройки" = "settings_app_tab"
# "О приложении" = "about_app_tab"
# "Об авторах" = "about_authors_tab"
"Зависимости" = "requirements_app_tab"

[TabCreatorsHide]
QUALITY = [
    "Настройки", "Зависимости"
]

[StaticPaths]
MODELS = "models"
IMAGES = "images"
FONTS = "fonts"
JS = "js"
DB = "db"
PUDS = "data/ПУДы.parquet"
PUDS_EMBEDDINGS = "data/ПУДы_эмбеддинги.safetensors"
RU_SUBJECTS = "data/Названия_дисциплин_для_эмбеддингов.parquet"
PUDS_SKILLS = "data/ПУДы_навыки.parquet"
COURSES_GRADES = "data/Оценки.parquet"
VACANCY = "data/Вакансии/Vacancy.parquet"

[DataframeHeaders]
RU_ID = "ID дисциплины БУП ППК (АСАВ)"
RU_SUBJECTS = [
    "Русскоязычное название дисциплины",
    "Факультет кафедры, предлагающей дисциплину",
    "Кампус кафедры, предлагающей дисциплину",
    "Кафедра, предлагающая дисциплину",
    "Уровень обучения",
    "Период изучения дисциплины",
    "Охват аудитории",
    "Формат изучения",
    "Ограничения: Курс студентов"
]
SUBJECTS_YEAR = "Период изучения дисциплины"
SUBJECTS_FULL = [
    "Аннотация",
    "Список разделов (названия и описания)",
    "Список планируемых результатов обучения РПУДа",
]
SUBJECTS_FULL_INFO = "full_info"
COURSES_GRADES = [
    "Средняя оценка",
    "Статистическая погрешность средней оценки",
    "Медианная оценка",
    "Статистическая погрешность медианной оценки",
    "Индекс сложности освоения курса №1 (метрика Вассерштейна)",
    "Статистическая погрешности индекса №1",
    "Индекс сложности освоения курса №2 (по средней оценке)",
    "Статистическая погрешности индекса №2",
    "Индекс сложности освоения курса №3 (по медианной оценке)",
    "Статистическая погрешности индекса №3",
]

[Settings]
DROPDOWN_ROLE = [
    "Руководитель образовательной программы",
    "Преподаватель",
    "Сотрудник учебного офиса",
    "Студент (история)",
    "Студент (филология)",
    "Студент (физика)",
    "Студент (социология и социальная Информатика)",
    "Студент (юриспруденция)",
    "Студент (МБ по бизнесу и экономике)",
    "Студент (Прикладной анализ данных и ИИ)",
    "Студент (дизайн)",
    "Другое",
]
USER_MAX_LENGTH = 40
TOP_SUBJECTS_RANGE = [5, 40]
TOP_SUBJECTS = 20
TOP_SUBJECTS_QUALITY = 10
MAX_SKILL_WORDS_RANGE = [1, 10]
MAX_SKILL_WORDS = 4
PRIORITY = [
    "Бакалавриат",
    "Специалитет",
    "Бакалавриат, Специалитет",
    "Бакалавриат, Магистратура",
    "Магистратура",
    "Аспирантура",
    "-",
    "nan",
]

[Models]
TASK = "text-matching"
SBERT = [
    "jina-embeddings-v3",
    "paraphrase-multilingual-MiniLM-L12-v2",
]
SBERT_VACANCY = [
    "LaBSE-en-ru"
]

[Requirements]
LIBRARY = "Библиотека"
RECOMMENDED_VERSION = "Рекомендованная версия"
CURRENT_VERSION = "Текущая версия"
